spring:
  application:
    name: gateway-service
  cloud:        # spring cloud gateway 路由配置方式
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
#      - id: 163                     #网关路由到网易官网
#        uri: http://www.163.com/
#        predicates:
#          - Path=/163/**
       - id: api-a
         # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
         uri: lb://FEGIN-SERVICE
         # 重点！转发该路径！,/api-a/**,
         predicates:
           - Path=/api-a/**
         # http://localhost:6601/api-a/hi?name=jianghong, 必须加上StripPrefix=1，否则访问服务时会带上api-a
         #而不是我们期望的去掉api-a，只保留**部分
         filters:
           - StripPrefix=1
#      - id: ORDER-SERVICE           #网关路由到订单服务order-service
#        uri: lb://ORDER-SERVICE
#        predicates:
#          - Path=/ORDER-SERVICE/**
#      - id: USER-SERVICE            #网关路由到用户服务user-service
#        uri: lb://USER-SERVICE
#        predicates:
#          - Pach=/USER-SERVICE/**

server:
  port: 5001


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


eureka:
  client:
    service-url:
      defaultZone: http://discovery2:8762/eureka,http://discovery1:8761/eureka

feign:
  hystrix:
    enabled: false